apiVersion: v1
kind: Service
metadata:
  name: udagram-api-feed-service
spec:
  selector:
    app.kubernetes.io/name: udagram-api-feed
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080